var GAME_LEVELS = [
  ["                                                                                ",
   "                                               yyyyyyy                          ",
   "                                             yyyyyyyyyyyy                       ",
   "                                              yyyyyyyyyy                        ",
   "                              yyy  c             yyyyyyy                        ",
   "                             yyyyyyy                                            ",
   "                          yyyyyy                          !             xxx     ",
   "                                              c    xx      xx    xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                      o            xx                            xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "        oo            xxx   !!   xxx                                        xx  ",
   "  xxxxxxxxxx         xxxx   xx               o o                             x  ",
   "  x              x       o                                                   x  ",
   "  x             x                         xxxxx                            o x  ",
   "  x          xxxx       o                 x                      oo          x  ",
   "  x  @       x  x                 c       x                      xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                         ",
   "                                      x!!x                     xxxx     xxxx                                      ",
   "                                      x!!xxxxxxxxxx           xx           xx                                     ",
   "                                      xx!!!!!!!!!!xx         xx             xx                                    ",
   "             xxxxxxxxxxxxxxxx!!!!!!!!!!xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                   o           xxxx!!!!!xxxx                 oo                   ",
   "                                               xxxxxxx            xxxxxxx        xxx         xxx                  ",
   "                                             o x!!!! x   oo                      x x         x x                  ",
   "                            !!               xxx     x                             x         x                    ",
   "                !!!!!      xxxx                x     x                       !!!!!!xx        x                    ",
   "                        o !             xx         x                 o   o   !!!!!!!x      o x                    ",
   "                       xxxx                    x     x      o  o     x   x   !!!!!!x       xxxx                   ",
   "               xxxxxx         xxx   xxx       xxx    x               x   x   !!!!!!x         x                    ",
   "              xx     xxo        x   x                x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x        xx     xx               x   x   x               x                    ",
   "     @       x         x!!!!!!! x   x                x               x   x   x   ooooo       x                    ",
   "    xxx      x         x!!!!!!! x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x!!!!!!! xx o xx        x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o      !!!!        xx!!!!!!xx !                    xx     xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       oxo                                                                    ",
   "                                       xxx            xx        xx          o                                 ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                     o x x                 !x!        !x!                             o       ",
   "               xxx                  xxx xxx                x          x         o                    xx       ",
   "              oxx                     x   x        xxx      x   oooo   x       xxx              ox!!!!        ",
   "             xxx         x            x   x                 x!        !x      x!!!x             x             ",
   "           xx                         x   x                 xxxxxxxxxxxx       xxx            o x             ",
   "         oo                          xx   xx    oox   xoo   x                                 x x             ",
   "         xxxx!!!!!xx                  x   xxxxxxxxx   xxxxxxxx              x x                x              ",
   "                           xx         x   x           x                    x!!!x               x              ",
   "                                     ox   x           x                     xxx                x              ",
   "                                 xx  xx   xx          x                                       x               ",
   "                                      x   x= = = =    x            xxxxx                                      ",
   "                                      x   x           x           x!!!x x      o                              ",
   "                                      x   x    = = = =x     o      xxx   xxxxxxx                              ",
   "                                     xx   xx          x                     x!!!x        o                    ",
   "                              o   o   x   x           x     x                xxv   xxxxxxxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                         o   xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx      xxxx         ",
   "                         x   x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx               o                        ",
   "                       !     xx           xx                                         xxx            x   oo    ",
   "  xxx                xxx        x     x     x                                         x!!!x        x     xxx  ",
   "  x!x                         x    xxx    x                                          xxx           x     x x  ",
   "  x!x             xx             x    xxx    xxxxxxx                   xx   xxxxx             o  xx        x  ",
   "  xxx                           x           x                        xx    x   x              xx           x  ",
   "  xxx                         xx          x         oo             xx    x x x              xx             x  ",
   "  xxx       @         oo                   x       |xxxx|    |xxxx|     xxx xxx                            x  ",
   "  xxx       xxx        xxx             o o    x                   x          x         xxx                 x  ",
   "  x    x   x  xxxxxxxxxxx       xx          x                     x       xxx       x!!!x         ox       x  ",
   "  x    x  x         oxxxo       x    xxx    x                             x x        xxx          xxx      x  ",
   "  x     o           xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx       x  ",
   "  x    xxx    oo  x       x           x!!x    x!!!!x    x!!!!x    xx   xx                    x             x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];
  [" xxx     xxx      xx     xx   xx       xx                    xx   xxx   xxx      xx"],
   "  xxx   xxx     xx  xx   xx   xx        xx                  xx    xxx   xx x     xx",
   "   xx   xx     xx    xx  xx   xx         xx      xxx       xx     xxx   xx  x    xx",
   "     xxxx      xx    xx  xx   xx          xx    xx xx     xx      xxx   xx   x   xx",
   "      xx       xx    xx  xx   xx           xx  xx   xx   xx       xxx   xx    x  xx",
   "      xx        xx  xx    x   x             xx x      x xx        xxx   xx     x xx",
   "      xx          xx       xxx                x        x          xxx   xx      xxx",
   "                                                                                   "]


if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
